name: jsontree
publish_to: none

repository: https://github.com/rtmigo/jsontree_dart

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # none :)

dev_dependencies:
  lints: ^2.0.0
  test: ^1.5.1
